# Generated by Django 2.2.5 on 2019-09-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('problem', models.CharField(max_length=20)),
                ('frequency', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=100)),
                ('last_mod', models.DateTimeField(auto_now_add=True)),
                ('sent_date', models.DateTimeField()),
                ('run_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
