# Generated by Django 2.2.6 on 2019-11-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
