# Generated by Django 2.2.5 on 2019-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0002_daemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='last_mod',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='daemon',
            name='run_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
