# Generated by Django 2.2.5 on 2019-09-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0003_auto_20190929_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daemon',
            name='last_mod',
        ),
    ]
