# Generated by Django 2.2.5 on 2019-09-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0004_remove_daemon_last_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daemon',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
