# Generated by Django 2.2.5 on 2019-09-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0005_auto_20190929_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daemon',
            old_name='description',
            new_name='dataset_description',
        ),
        migrations.AddField(
            model_name='daemon',
            name='run_description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
