# Generated by Django 2.2.5 on 2019-09-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg', '0006_auto_20190929_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='daemon',
            name='clean',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daemon',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daemon',
            name='params',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='daemon',
            name='scaling',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daemon',
            name='training',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
